theme: jekyll-theme-minimal
plugins: 
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jemoji
title: czhc.io
description: beta 
google_analytics: UA-133008676-1
sass: 
  sass_dir: _sass
  style: compressed
permalink: /:categories/:year/:month/:day/:title

# Conversion
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  extensions: fenced_code_blocks
collections_dir: collections 
collections: 
  projects: 
    output: true
    permalink: /projects/:title
  posts: 
    output : true
defaults:
  - scope: 
      path: ""
      type: projects
    values:
      layout: project
      permalink: projects/:title
      category: projects
  - scope: 
      type: posts
    values: 
      layout: post 
      permalink: /:year/:month/:day/:title

pagination: 
  debug: true
  per_page: 10

 
