theme: jekyll-theme-minimal
plugins: 
  - jekyll-sitemap
  - jekyll-paginate-v2
title: czhc.io
description: beta 
google_analytics: UA-133008676-1
sass: 
  sass_dir: _sass
  style: compressed
permalink: /:categories/:year/:month/:day/:title

# Conversion
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  extensions: fenced_code_blocks
defaults:
  - scope: 
      path: "_posts/projects"
      type: posts
    values:
      layout: project
      permalink: projects/:title
      category: projects
  - scope:
      path: "_posts/guides"
      type: posts
    values: 
      layout: default
      permalink: guides/:year/:month/:day/:title
      category: guides
pagination: 
  debug: true
  per_page: 10
#collections: 
#  projects: 
#    output: true
#    permalink: /projects/:title
