theme: jekyll-theme-minimal
plugins: 
  - jekyll-sitemap
title: czhc.io
description: work in progress
google_analytics: UA-133008676-1
sass: 
  sass_dir: _sass
  style: compressed
permalink: /:categories/:year/:month/:day/:title
